### ISSUE TITLE
[HxModal] Close button improper layout when custom icon is used

### ISSUE THREAD

**Issue by Xopabyteh** [havit/Havit.Blazor#1080]
When I change the default icon of HxModal
```cs
HxModal.Defaults.CloseButtonIcon = MyIcons.Close;
```

The close buttons on the modal loses its layout styling, because of [these lines](https://github.com/havit/Havit.Blazor/blob/0f0222553db05959c665a57bebf207111849ea71/Havit.Blazor.Components.Web.Bootstrap/Modals/HxModal.razor#L23):
```cs
if (CloseButtonIconEffective is null)
{
	<button type="button" class="btn-close text-reset" data-bs-dismiss="modal" aria-label="Close"></button>
}
else
{
	<div role="button" data-bs-dismiss="modal" aria-label="Close"><HxIcon Icon="CloseButtonIconEffective"/></div>
}
```
where the close button loses the `btn-close`, which is used internally in bootstrap like so:
```css
.modal-header .btn-close {
    padding: calc(var(--bs-modal-header-padding-y) * .5) calc(var(--bs-modal-header-padding-x) * .5);
    margin-top: calc(-.5 * var(--bs-modal-header-padding-y));
    margin-right: calc(-.5 * var(--bs-modal-header-padding-x));
    margin-bottom: calc(-.5 * var(--bs-modal-header-padding-y));
    margin-left: auto;
}
```
