### ISSUE TITLE
Default margin-bottom for inputs in form?

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#6]
Currently there is margin-bottom "for all inputs in form, if it is not the only child":

```css
form .hx-form-group:not(:only-child),
form .hx-autosuggest:not(:only-child),
form .form-check:not(:only-child),
form .form-switch:not(:only-child),
form .hx-input-tags:not(:only-child) {
  margin-bottom: var(--hx-form-spacing);
}
```

...which is something we want for basic form layout, but might cause unexpected effects for forms+inputs used in navbars, dropdowns, standalone and such specific situations:
![image](https://user-images.githubusercontent.com/12828888/134250765-95604fb2-d845-45ea-abb6-715051f5cc1d.png)

We might try to look for better CSS selector to limit the side-effects.
