### ISSUE TITLE
[doc] On this page navigation links are broken - headings are hidden under Navbar

### ISSUE THREAD

**Issue by crdo** [havit/Havit.Blazor#931]
If you click on a link in on this page navigation, the referred link is hidden under the Navbar.
We need to set offset.

**Comment by hakenr** [comment]
@crdo Could you find a minute to fix this?

The solution should be something like this (with a media query added to avoid offsetting the content when the navbar isn't shown):
```css
html {
    scroll-padding-top: 70px; /* height of sticky header, to prevent the header from hiding content when jumping to it */
}
```
